services:
  mysqldb:
    image: mysql:5.7.16
    command: [ "--explicit_defaults_for_timestamp" ] # Adiciona a flag necessária
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysqlvolume:/var/lib/mysql

  app:
    image: ${REGION}-docker.pkg.dev/${GCP_PROJECT}/${REPOSITORY_NAME}/${IMAGE_NAME}:latest
    container_name: rest-api-spring-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/${MYSQLDB_DATABASE}?useSSL=false&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=${MYSQLDB_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true

volumes:
  mysqlvolume:
